error_log /tmp/error.log warn;

map $sent_http_content_type $cache_control {
  default                   "no-cache, no-store, must-revalidate";
  ~text/html                "no-cache, no-store, must-revalidate";
  ~text/css                 "max-age=31536000, public";
  ~application/javascript   "max-age=31536000, public";
  ~application/octet-stream "max-age=31536000, public";
  ~image/                   "max-age=31536000, public";
  ~font/                    "max-age=31536000, public";
}

server {
  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_static on;
  gzip_types text/plain text/css application/javascript application/x-javascript text/javascript application/json text/xml image/gif image/png image/jpeg image/webp image/svg+xml application/octet-stream;

  listen 8080;
  server_name _;

  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header Cache-Control $cache_control;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  location /assets/ {
    root /usr/share/nginx/html;

    add_header X-Frame-Options "";
    add_header X-XSS-Protection "";
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, OPTIONS";
    add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";
  }
}
