apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: customer
  title: Zákaznický servis
  annotations:
    glossary/color: "#dc2626"
    glossary/icon: "🎧"
spec:
  owner: glossary-owners
