apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: label--logistics
  title: Label
  description: Samolepicí papír s čárovým kódem EAN kódem nebo AWB číslem nalepený na balík nebo produkt pro identifikaci.
  annotations:
    glossary/term-cs: Etiketa
    glossary/term-en: Label
    glossary/term-ro: Etichetă
    glossary/term-it: Etichetta
    glossary/term-ua: Етикетка
    glossary/term-pl: Etykieta
    glossary/en-gui: Label
    glossary/en-code: Label
    glossary/domain: "logistics"
  tags:
    - vocabulary
    - logistics
spec:
  type: vocabulary-term
  owner: glossary-owners
  domain: logistics
